inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable

Metrics/AbcSize:
  Exclude:
    - 'app/services/sde/**/*.rb'
    - 'db/migrate/*'
    - 'lib/**/*.rake'

Metrics/BlockLength:
  Exclude:
    - 'db/migrate/*'
    - 'lib/**/*.rake'
    - 'spec/factories/**/*.rb'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'db/migrate/*'
    - 'lib/**/*.rake'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/sde/**/*.rb'
    - 'lib/capistrano/**/*.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/sde/**/*.rb'
    - 'lib/capistrano/**/*.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/services/sde/**/*.rb'
    - 'db/migrate/*'
    - 'lib/**/*.rake'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 180

Rails/I18nLocaleTexts:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - 'lib/capistrano/**/*.rake'

Rails/SkipsModelValidations:
  Exclude:
    - 'lib/tasks/data.rake'
