# syntax = docker/dockerfile:1.0-experimental
FROM ruby:3.0-alpine
LABEL maintainer="shahni@bokobo.space"

# Add basic packages
RUN apk add --no-cache \
      build-base \
      curl-dev \
      postgresql-client \
      postgresql-dev \
      git \
      nodejs \
      redis \
      yarn \
      tzdata \
      file

WORKDIR /app

COPY package.json yarn.lock /app/
RUN yarn install --frozen-lockfile

COPY Gemfile* /app/
RUN gem install bundler -v 2.2.23 && gem cleanup bundler
RUN bundle config --local frozen 1 && \
    bundle install -j4 --retry 3

EXPOSE 3000
EXPOSE 3035

CMD ["bundle", "exec", "rails", "console"]
