# syntax = docker/dockerfile:1.0-experimental
FROM ruby:3.0-alpine
LABEL maintainer="shahni@bokobo.space"

# Add basic packages
RUN apk add --no-cache \
      build-base \
      curl-dev \
      postgresql-client \
      postgresql-dev \
      git \
      nodejs \
      redis \
      yarn \
      tzdata \
      file

WORKDIR /app

RUN gem update --system && \
    gem install bundler -v 2.3.5
