# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

gem 'dotenv-rails', '~> 2.7'

gem 'active_median', '~> 0.3'
gem 'activerecord-copy', '~> 1.1'
gem 'activerecord-import', '~> 1.2'
gem 'ahoy_matey', '~> 4.0'
gem 'ancestry', '~> 4.1'
gem 'awesome_print', '~> 1.9'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'composite_primary_keys', '~> 13.0'
gem 'discard', '~> 1.2'
gem 'down', '~> 5.2'
gem 'esi-sdk', '~> 2.1'
gem 'flamegraph', '~> 0.9'
gem 'groupdate', '~> 5.2'
gem 'heroicon', '~> 0.4'
gem 'hiredis', '~> 0.6'
gem 'http', '~> 5.0'
gem 'hotwire-rails', '~> 0.1'
gem 'jbuilder', '~> 2.7'
gem 'kredis', '~> 1.0'
gem 'listen', '~> 3.3'
gem 'local_time', '~> 2.1'
gem 'lockbox', '~> 0.6'
gem 'lograge', '~> 0.11'
gem 'memory_profiler', '~> 1.0'
gem 'nanoid', '~> 2.0'
gem 'oauth2', '~> 1.4'
gem 'oj', '~> 3.13'
gem 'omniauth-eve_online-sso', '~> 0.5'
gem 'omniauth-rails_csrf_protection', '~> 1.0'
gem 'pagy', '~> 5.6'
gem 'paper_trail', '~> 12.1'
gem 'pg', '~> 1.1'
gem 'pghero', '~> 2.8'
gem 'pg_query', '~> 2.1'
gem 'pg_search', '~> 2.3'
gem 'pry-rails', '~> 0.3'
gem 'puma', '~> 5.0'
gem 'pundit', '~> 2.1'
gem 'rack-mini-profiler', '~> 2.0'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'repost', '~> 0.3'
gem 'retriable', '~> 3.1'
gem 'rollups', '~> 0.1'
gem 'ruby-limiter', '~> 2.1'
gem 'scenic', '~> 1.5'
gem 'sidekiq', '~> 6.3'
gem 'sidekiq-batch', '~> 0.1'
gem 'sidekiq-scheduler', '~> 3.1'
gem 'sidekiq-status', '~> 2.1'
gem 'sidekiq-throttled', '~> 0.13'
gem 'sidekiq-unique-jobs', '~> 7.1'
gem 'stackprof', '~> 0.2'
gem 'stimulus-rails', '~> 0.7'
gem 'tty-command', '~> 0.10'
gem 'tty-table', '~> 0.12'
gem 'turbo-rails', '~> 0.9'
gem 'typhoeus', '~> 1.4'
gem 'view_component', '~> 2.46'
gem 'webpacker', '~> 5.4.0'

group :development, :test do
  gem 'byebug', '~> 11.1'
  gem 'rspec-rails', '~> 5.0'
end

group :development do
  gem 'annotate', '~> 3.1'
  gem 'bcrypt_pbkdf', '~> 1.1'
  gem 'capistrano', '~> 3.16'
  gem 'capistrano3-puma', '~> 5.2'
  gem 'capistrano-bundler', '~> 2.0'
  gem 'capistrano-rails', '~> 1.6'
  gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq'
  gem 'ed25519', '~> 1.2'
  gem 'rubocop', '~> 1.23'
  gem 'rubocop-performance', '~> 1.12'
  gem 'rubocop-rails', '~> 2.12'
  gem 'rubocop-rspec', '~> 2.6'
  gem 'web-console', '>= 4.1.0'
end
