_primary: &primary
  adapter: postgres
  url: <%= ENV['ASSET_PRECOMPILE'].present? ? 'nulldb://user:pass@127.0.0.1/dbname' : ENV.fetch('DATABASE_URL', 'eve_indy_watch') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

development:
  <<: *primary

test:
  <<: *primary
  url: <%= ENV['ASSET_PRECOMPILE'].present? ? 'nulldb://user:pass@127.0.0.1/dbname' : ENV.fetch('DATABASE_URL', 'eve_indy_watch') + '_test' %>

staging:
  <<: *primary

production:
  <<: *primary
