:schedule:
  sync_all_contracts_from_esi:
    cron: '*/5 * * * *'
    class: 'Corporation::SyncAllContractsFromESIWorker'
    description: "Sync contracts for all corporations with contract sync enabled"

  import_all_killmails_from_zkb:
    cron: '*/5 * * * *'
    class: 'Alliance::FetchAllKillmailsFromZKBWorker'
    description: "Import killmails for all alliances with killmail sync enabled"

  sync_industry_indices_from_esi:
    cron: '0 * * * *'
    class: 'IndustryIndexSnapshot::SyncFromESIWorker'
    description: "Create a snapshot of industry indices"

  sync_market_prices_from_esi:
    cron: '0 * * * *'
    class: 'MarketPriceSnapshot::SyncFromESIWorker'
    description: "Create a snapshot of market prices"

  preload_region_type_histories:
    cron: '15 11 * * *'
    class: 'Region::PreloadTypeHistoriesWorker'
    description: "Preload type histories for items in contracts, fittings, and killmails"

  calculate_live_stock_levels:
    cron: '*/5 * * * *'
    class: 'Fitting::CalculateAllStockLevelsWorker'
    args: ['live']
    description: "Calculate live stock levels"

  prune_live_stock_levels:
    cron: '*/5 * * * *'
    class: 'Fitting::PruneLiveStockLevelsWorker'
    description: "Prune live stock levels older than the configured time"

  calculate_end_of_day_stock_levels:
    cron: '0 11 * * *'
    class: 'Fitting::CalculateAllStockLevelsWorker'
    args: ['end_of_day']
    description: "Calculate end-of-day stock levels"

  calculate_end_of_week_stock_levels:
    cron: '0 11 * * 7'
    class: 'Fitting::CalculateAllStockLevelsWorker'
    args: ['end_of_week']
    description: "Calculate end-of-week stock levels"

  calculate_end_of_month_stock_levels:
    cron: '0 11 1 * *'
    class: 'Fitting::CalculateAllStockLevelsWorker'
    args: ['end_of_month']
    description: "Calculate end-of-month stock levels"

  ingest_all_markets:
    cron: '* * * * *'
    class: 'Market::IngestAllWorker'
    description: "Ingest market locations and run aggregations for all markets"

  expire_order_snapshot_keys:
    cron: '*/15 * * * *'
    class: 'Location::ExpireSnapshotKeysWorker'
    description: "Scan orders database to ensure old keys are expired"

  expire_market_snapshot_keys:
    cron: '*/15 * * * *'
    class: 'Market::ExpireSnapshotKeysWorker'
    description: "Scan markets database to ensure old keys are expired"
