production: &production
  url: <%= ENV.fetch("LOCATIONS_WRITER_REDIS_URL", "redis://127.0.0.1:6376/3") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("LOCATIONS_WRITER_REDIS_URL", "redis://127.0.0.1:6376/3") %>
  timeout: 1

staging: &staging
  url: <%= ENV.fetch("LOCATIONS_WRITER_REDIS_URL", "redis://127.0.0.1:6376/3") %>
  timeout: 1

test:
  url: <%= ENV.fetch('TEST_LOCATIONS_WRITER_REDIS_URL', "redis://127.0.0.1:6379/9") %>
