production: &production
  url: <%= ENV.fetch("MARKETS_WRITER_REDIS_URL", "redis://127.0.0.1:6376/2") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("MARKETS_WRITER_REDIS_URL", "redis://127.0.0.1:6376/2") %>
  timeout: 1

staging: &staging
  url: <%= ENV.fetch("MARKETS_WRITER_REDIS_URL", "redis://127.0.0.1:6376/2") %>
  timeout: 1

test:
  url: <%= ENV.fetch('MARKETS_WRITER_REDIS_URL', "redis://127.0.0.1:6379/10") %>
