production: &production
  url: <%= ENV.fetch("MARKETS_READER_REDIS_URL", "redis://127.0.0.1:6375/2") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("MARKETS_READER_REDIS_URL", "redis://127.0.0.1:6375/2") %>
  timeout: 1

staging: &staging
  url: <%= ENV.fetch("MARKETS_READER_REDIS_URL", "redis://127.0.0.1:6375/2") %>
  timeout: 1

test:
  url: <%= ENV.fetch('TEST_MARKETS_READER_REDIS_URL', "redis://127.0.0.1:6379/10") %>
