production: &production
  url: <%= ENV.fetch("ORDERS_READER_REDIS_URL", "redis://127.0.0.1:6375/1") %>
  timeout: 1

development: &development
  url: <%= ENV.fetch("ORDERS_READER_REDIS_URL", "redis://127.0.0.1:6375/1") %>
  timeout: 1

staging: &staging
  url: <%= ENV.fetch("ORDERS_READER_REDIS_URL", "redis://127.0.0.1:6375/1") %>
  timeout: 1

test:
  url: <%= ENV.fetch('TEST_ORDERS_READER_REDIS_URL', "redis://127.0.0.1:6379/11") %>
